# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules

segmentation_modules = collect_submodules('segmentation_annotator')

ultralytics_runtime_modules = [
    'ultralytics',
    'ultralytics.cfg',
    'ultralytics.data',
    'ultralytics.data.augment',
    'ultralytics.data.base',
    'ultralytics.data.build',
    'ultralytics.data.converter',
    'ultralytics.data.dataset',
    'ultralytics.data.loaders',
    'ultralytics.data.utils',
    'ultralytics.engine',
    'ultralytics.engine.model',
    'ultralytics.engine.predictor',
    'ultralytics.engine.results',
    'ultralytics.engine.trainer',
    'ultralytics.engine.validator',
    'ultralytics.hub',
    'ultralytics.hub.auth',
    'ultralytics.hub.session',
    'ultralytics.hub.utils',
    'ultralytics.models',
    'ultralytics.models.fastsam',
    'ultralytics.models.fastsam.model',
    'ultralytics.models.fastsam.predict',
    'ultralytics.models.fastsam.utils',
    'ultralytics.models.fastsam.val',
    'ultralytics.models.nas',
    'ultralytics.models.nas.model',
    'ultralytics.models.nas.predict',
    'ultralytics.models.nas.val',
    'ultralytics.models.rtdetr',
    'ultralytics.models.rtdetr.model',
    'ultralytics.models.rtdetr.predict',
    'ultralytics.models.rtdetr.train',
    'ultralytics.models.rtdetr.val',
    'ultralytics.models.sam',
    'ultralytics.models.sam.amg',
    'ultralytics.models.sam.model',
    'ultralytics.models.sam.predict',
    'ultralytics.models.yolo',
    'ultralytics.models.yolo.classify',
    'ultralytics.models.yolo.classify.predict',
    'ultralytics.models.yolo.classify.train',
    'ultralytics.models.yolo.classify.val',
    'ultralytics.models.yolo.detect',
    'ultralytics.models.yolo.detect.predict',
    'ultralytics.models.yolo.detect.train',
    'ultralytics.models.yolo.detect.val',
    'ultralytics.models.yolo.model',
    'ultralytics.models.yolo.obb',
    'ultralytics.models.yolo.obb.predict',
    'ultralytics.models.yolo.obb.train',
    'ultralytics.models.yolo.obb.val',
    'ultralytics.models.yolo.pose',
    'ultralytics.models.yolo.pose.predict',
    'ultralytics.models.yolo.pose.train',
    'ultralytics.models.yolo.pose.val',
    'ultralytics.models.yolo.segment',
    'ultralytics.models.yolo.segment.predict',
    'ultralytics.models.yolo.segment.train',
    'ultralytics.models.yolo.segment.val',
    'ultralytics.models.yolo.world',
    'ultralytics.models.yolo.world.train',
    'ultralytics.models.yolo.world.train_world',
    'ultralytics.models.yolo.yoloe',
    'ultralytics.models.yolo.yoloe.predict',
    'ultralytics.models.yolo.yoloe.train',
    'ultralytics.models.yolo.yoloe.train_seg',
    'ultralytics.models.yolo.yoloe.val',
    'ultralytics.nn',
    'ultralytics.nn.autobackend',
    'ultralytics.nn.modules',
    'ultralytics.nn.modules.block',
    'ultralytics.nn.modules.conv',
    'ultralytics.nn.modules.head',
    'ultralytics.nn.modules.transformer',
    'ultralytics.nn.modules.utils',
    'ultralytics.nn.tasks',
    'ultralytics.utils',
    'ultralytics.utils.autobatch',
    'ultralytics.utils.callbacks',
    'ultralytics.utils.callbacks.base',
    'ultralytics.utils.checks',
    'ultralytics.utils.dist',
    'ultralytics.utils.downloads',
    'ultralytics.utils.errors',
    'ultralytics.utils.files',
    'ultralytics.utils.git',
    'ultralytics.utils.instance',
    'ultralytics.utils.loss',
    'ultralytics.utils.metrics',
    'ultralytics.utils.nms',
    'ultralytics.utils.ops',
    'ultralytics.utils.patches',
    'ultralytics.utils.plotting',
    'ultralytics.utils.tal',
    'ultralytics.utils.torch_utils',
    'ultralytics.utils.tqdm',
]

hiddenimports = sorted(set(segmentation_modules + ultralytics_runtime_modules))


a = Analysis(
    ['segmentation_annotator\\main.py'],
    pathex=['segmentation_annotator'],
    binaries=[],
    datas=[('best.pt', '.')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='segmentation_annotator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='segmentation_annotator',
)
